branches:
  only: [master, develop]
# sign in at https://travis-ci.org/#
#
# https://github.com/travis-ci/travis-ci/issues/2197#issuecomment-41177752
# before_install:
#  - brew update
#  - brew upgrade xctool
#
# http://docs.travis-ci.com/user/languages/objective-c/
language: objective-c
osx_image: xcode7.3
xcode_sdk:
- iphonesimulator
xcode_project: MROGeometry.xcodeproj
xcode_scheme: MROGeometry
